import { IsNotEmpty } from 'class-validator';
export class CreatePersonaDto {
  //  model dat_persona
  //  id_persona            String                 @id @default(dbgenerated("f_nuevouuid()")) @db.VarChar(36)
  @IsNotEmpty()
  numero: number; //?               @db.Decimal(4, 0)
  @IsNotEmpty()
  ci: string; //?                @db.VarChar(15)
  @IsNotEmpty()
  nombre: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  apellido1: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  apellido2: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  fecha_nac: string; //?              @db.Date
  @IsNotEmpty()
  sexo: string; //?                @db.VarChar(1)
  @IsNotEmpty()
  raza: string; //?                @db.VarChar(1)
  @IsNotEmpty()
  peso: string; //?               @db.Decimal(4, 1)
  @IsNotEmpty()
  estatura: string; //?               @db.Decimal(3, 2)
  @IsNotEmpty()
  madre: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  padre: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  estado_civil: string; //?                @db.VarChar(10)
  @IsNotEmpty()
  talla_camisa: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  talla_pantalon: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  num_zapato: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  direccion: string; //?                @db.VarChar(100)
  @IsNotEmpty()
  provincia: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  municipio: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  reparto: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  telefono: string; //?                @db.VarChar(20)
  @IsNotEmpty()
  correo_electronico: string; //?                @db.VarChar(100)
  @IsNotEmpty()
  militar: string; //?                @db.VarChar(2)
  @IsNotEmpty()
  fecha_ing_far: string; //?              @db.Date
  @IsNotEmpty()
  id_grado_militar: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  id_cargo_militar: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  id_especialidad: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  pcc: string; //?                @db.VarChar(2)
  @IsNotEmpty()
  ujc: string; //?                @db.VarChar(2)
  @IsNotEmpty()
  id_fuente_procedencia: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  nivel_cultural: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  lugar_graduacion: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  fecha_graduacion: string; //?              @db.Date
  @IsNotEmpty()
  pais_graduacion: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  cat_docente: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  cat_cientifica: string; //?                @db.VarChar(50)
  @IsNotEmpty()
  master: string; //?                @db.VarChar(2)
  @IsNotEmpty()
  gdocientifico: string; //?                @db.VarChar(20)
  @IsNotEmpty()
  baja_propuesta: string; //?                @db.VarChar(2)
  @IsNotEmpty()
  id_registro_militar: string; //?                @db.VarChar(36)
  @IsNotEmpty()
  defensa: string; //?                @db.VarChar(30)
  @IsNotEmpty()
  imagen: any; //?      Bytes?
  @IsNotEmpty()
  imagen_nombre: string; //?                @db.VarChar(30)
}
